[mongodb]
mongodb.venkatesh.fun

[redis]
redis.venkatesh.fun

[mysql]
mysql.venkatesh.fun

[rabbitmq]
rabbitmq.venkatesh.fun

[catalogue]
catalogue.venkatesh.fun

[cart]
cart.venkatesh.fun

[user]
user.venkatesh.fun

[local]
localhost

[all:vars]
ansible_user=ec2-user
ansible_password=DevOps321

[local:vars]
NAME=from inventory
; COURSE=Ansible
; DURATION=10HRS
; TRAINER=Sivakumar